services:
  api:
    build: .
    container_name: urlshortener-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
      - flyway

  db:
    image: postgres:15
    container_name: urlshortener-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: urlshortener-flyway
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_URL: jdbc:postgresql://db:5432/urlshortener
    command: migrate
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  postgres_data:
